# Generated by Django 4.2.7 on 2024-02-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='new_reports',
            field=models.FileField(blank=True, null=True, upload_to='new_reports/'),
        ),
    ]
