# Generated by Django 4.2.7 on 2024-02-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appointment_new_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='new_reports',
        ),
        migrations.CreateModel(
            name='NewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='new_reports/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_reports', to='home.appointment')),
            ],
        ),
    ]
